name: Release CI

on:
  push:
    branches:
      - dev
      - pre
  release:
    types: [published]

jobs:
  build-and-dockerize:
    name: Build & Docker Image
    runs-on: ubuntu-latest

    # Allow:
    # - push on dev/pre
    # - release only if coming from main
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'release' && github.event.release.target_commitish == 'main')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: |
          DATE=$(date +%Y-%m%d)
          SHORT_SHA=${GITHUB_SHA::7}

          if [[ "${{ github.event_name }}" == "release" ]]; then
            IMAGE_TAG="v${DATE}-${SHORT_SHA}-prod"
          else
            IMAGE_TAG="v${DATE}-${SHORT_SHA}"
          fi

          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Log image tag
        run: echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT