name: Release CI

on:
  release:
    types: [published]

jobs:
  build-and-dockerize:
    name: Build & Docker Image
    runs-on: ubuntu-latest

    # Ensure the release/tag comes from main branch
    if: github.event.release.target_commitish == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: |
          DATE=$(date +%Y-%m%d)
          SHORT_SHA=${GITHUB_SHA::7}
          IMAGE_TAG="v${DATE}-${SHORT_SHA}"
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Log image tag
        run: echo "Docker image tag -> ${{ steps.vars.outputs.image_tag }}"