name: Release CI

on:
  push:
    branches:
      - dev
      - pre
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-dockerize:
    name: Build & Docker Image
    runs-on: ubuntu-latest

    # Allow:
    # - push on dev/pre
    # - release only if coming from main
    # - workflow_dispatch on any branch except main
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'release' && github.event.release.target_commitish == 'main') ||
      (github.event_name == 'workflow_dispatch' && github.ref_name != 'main')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: |
          DATE=$(date +%Y.%-m.%-d)
          SHORT_SHA=${GITHUB_SHA::7}

          if [[ "${{ github.event_name }}" == "release" ]]; then
            IMAGE_TAG="${DATE}-${SHORT_SHA}-${{ github.ref_name }}"
          else
            IMAGE_TAG="${DATE}-${SHORT_SHA}"
          fi

          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Log image tag
        run: echo "image_tag=${{ steps.vars.outputs.image_tag }}"